repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(\.next/|node_modules/|generated/)
      - id: check-yaml
      - id: check-json
        exclude: ^(\.next/|node_modules/)
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: detect-private-key